import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-stone-900 bg-stone-100 flex flex-grow h-screen flex-col`}
      >
        <main className="grid items-center justify-items-center h-full dark:bg-stone-900 bg-stone-100 w-full p-5">
          {children}
        </main>
        <footer className="p-2">
          Copyright &copy; 2024 Johannes Thorén
        </footer>
      </body>
    </html>
  );
}
